In [2]:
# import sys
# sys.path.remove('//anaconda/lib/python2.7/site-packages')
# sys.path.append('/global/homes/d/dorislee/anaconda/lib/python2.7/site-packages')  

In [1]:
cd /project/projectdirs/astro250/doris/halo/darksky_catalog/

/global/project/projectdirs/astro250/doris/halo/darksky_catalog


Need to install thingking again

In [2]:
import yt
import numpy as np
# from enhance import enhance
from numpy import float64
#I added an empty __init__.py so that the modules can detect what's inside the darksky/ directory
# from darksky_tour.enhance import enhance
from yt.utilities.lib.image_utilities import add_rgba_points_to_image
from darksky_catalog import darksky

In [3]:
# Define a bounding box of 100 Mpc on a side.
center = np.array([-2505805.31114929,  -3517306.7572399, -1639170.70554688])
width = 50.0e3 # 5 Mpc
bbox = np.array([center-width/2, center+width/2])
ds = darksky['ds14_a']#['halos_a'].load(bounding_box = "None", midx = 7)
print ds.datasets

[DarkSkySDFHaloCatalog: halos_a_1.0000, DarkSkySDFFullOutput: full_data_a_1.0000, DarkSkyFilteredHaloCatalog: filtered_1e15_a_1.0000]


tried to fix by [this](https://bitbucket.org/yt_analysis/yt/pull-requests/1862/bugfix-fix-python-35-tests/diff) but this didn't help '

In [5]:
halo = darksky['ds14_a']['halos_a_1.0000'].load(bounding_box = "None", midx = 7)
type(halo)

yt : [INFO     ] 2015-11-26 02:08:41,181 Building memmap with offset: 1216 and size 256
yt : [INFO     ] 2015-11-26 02:08:41,215 Building memmap with offset: 7360 and size 4675339354


HTTPSDFREAD


TypeError: Cannot cast ufunc multiply output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [1]:
cd /project/projectdirs/astro250/doris/halo/darksky_catalog/

/global/project/projectdirs/astro250/doris/halo/darksky_catalog


In [2]:
import yt
import numpy as np
# from enhance import enhance
from numpy import float64
#I added an empty __init__.py so that the modules can detect what's inside the darksky/ directory
# from darksky_tour.enhance import enhance
from yt.utilities.lib.image_utilities import add_rgba_points_to_image
from darksky_catalog import darksky
# Define a bounding box of 100 Mpc on a side.
center = np.array([-2505805.31114929,  -3517306.7572399, -1639170.70554688])
width = 50.0e3 # 5 Mpc
bbox = np.array([center-width/2, center+width/2])
ds = darksky['ds14_a']#['halos_a'].load(bounding_box = "None", midx = 7)
print ds.datasets

[DarkSkySDFHaloCatalog: halos_a_1.0000, DarkSkySDFFullOutput: full_data_a_1.0000, DarkSkyFilteredHaloCatalog: filtered_1e15_a_1.0000]


In [3]:
arr = np.array([0,0,0],dtype=np.float64)
val = 1.0
arr *=val

In [4]:
arr

array([ 0.,  0.,  0.])

In [3]:
halo = darksky['ds14_a']['halos_a_1.0000'].load(bounding_box = "None", midx = 7)
type(halo)

yt : [INFO     ] 2015-11-26 05:51:27,078 Building memmap with offset: 1216 and size 256
yt : [INFO     ] 2015-11-26 05:51:27,116 Building memmap with offset: 7360 and size 4675339354
yt : [INFO     ] 2015-11-26 05:51:27,164 Calculating time to be 4.342e+17 seconds
yt : [INFO     ] 2015-11-26 05:51:27,192 Parameters: current_time              = 4.34205871754e+17
yt : [INFO     ] 2015-11-26 05:51:27,193 Parameters: domain_dimensions         = [2 2 2]
yt : [INFO     ] 2015-11-26 05:51:27,194 Parameters: domain_left_edge          = [ 0.  0.  0.]
yt : [INFO     ] 2015-11-26 05:51:27,195 Parameters: domain_right_edge         = [ 8000.  8000.  8000.]
yt : [INFO     ] 2015-11-26 05:51:27,195 Parameters: cosmological_simulation   = 1
yt : [INFO     ] 2015-11-26 05:51:27,196 Parameters: current_redshift          = 0.0
yt : [INFO     ] 2015-11-26 05:51:27,196 Parameters: omega_lambda              = 0.704874
yt : [INFO     ] 2015-11-26 05:51:27,197 Parameters: omega_matter              = 0.295126


yt.frontends.sdf.data_structures.SDFDataset

Okay bug fixed...moving on.

In [7]:
filtered_catalog =darksky['ds14_a']['filtered_1e15_a_1.0000']

In [6]:
darksky['ds14_a'].datasets

[DarkSkySDFHaloCatalog: halos_a_1.0000,
 DarkSkySDFFullOutput: full_data_a_1.0000,
 DarkSkyFilteredHaloCatalog: filtered_1e15_a_1.0000]

In [14]:
yt.funcs.mylog.setLevel(50)

In [15]:
filtered_catalog.get_halo(3)

HTTPSDFREAD
<type 'numpy.float64'>
1.0
<type 'numpy.ndarray'>
[0 0 0]


(2573.74609375, 4400.4296875, 2438.5810546875, 170.69931030273438, -178.6830596923828, -269.6794738769531, 5967416286773248.0, 7118018161147904.0, 4287023217115136.0, 2829745376985088.0, 859232098320384.0, 2682.095947265625, 1804.38330078125, 4.698720455169678, 0.024555811658501625, 0.6881513595581055, 22578031121, -1)

In [16]:
ds = filtered_catalog.load()

In [17]:
filtered_catalog.get_halo(136591)

HTTPSDFREAD
<type 'numpy.float64'>
1.0
<type 'numpy.ndarray'>
[0 0 0]


(2726.94287109375, 3072.8818359375, 641.2564697265625, -68.32164764404297, 105.40631103515625, 122.46353912353516, 927564558237696.0, 1000036024451072.0, 826901060911104.0, 647010919120896.0, 135844958568448.0, 1645.4683837890625, 971.8765869140625, 2.442671775817871, 0.045493233948946, 0.7754606604576111, 3573634164, -1)

In [18]:
def get_halo(self, n):
        ds = self.load()
        offset = ds['id'][n]
        catalog = self.parent[self.halo_catalog].load(midx = -1)
#         return catalog
        return  catalog.sdf_container.structs
#         halo = catalog.sdf_container.structs[-1][offset][0]
#         return halo

In [19]:
get_halo(filtered_catalog,4)

HTTPSDFREAD
<type 'numpy.float64'>
1.0
<type 'numpy.ndarray'>
[0 0 0]


In [20]:
get_halo(filtered_catalog,4)[-1][10]

HTTPSDFREAD
<type 'numpy.float64'>
1.0
<type 'numpy.ndarray'>
[0 0 0]


array([ (13.368721008300781, 3.1736860275268555, 7.173592567443848, 83.88713836669922, -115.49732208251953, -169.82952880859375, 663801167872.0, 780942573568.0, 468565557248.0, 390471286784.0, 0.0, 139.84893798828125, 85.87332153320312, 0.22493979334831238, 0.08961829543113708, 0.7047524452209473, 3, -1)], 
      dtype=[('x', '<f4'), ('y', '<f4'), ('z', '<f4'), ('vx', '<f4'), ('vy', '<f4'), ('vz', '<f4'), ('mvir', '<f4'), ('m200b', '<f4'), ('m200c', '<f4'), ('m500c', '<f4'), ('m2500c', '<f4'), ('vmax', '<f4'), ('rvmax', '<f4'), ('r200b', '<f4'), ('spin', '<f4'), ('kin_to_pot', '<f4'), ('id', '<i8'), ('pid', '<i8')])

In [27]:
get_halo(filtered_catalog,136591)[-1][136591]#[0]

HTTPSDFREAD
<type 'numpy.float64'>
1.0
<type 'numpy.ndarray'>
[0 0 0]


array([ (151.07432556152344, 217.76809692382812, 208.54818725585938, 243.1653289794922, -265.89288330078125, 470.3860778808594, 468565557248.0, 663801167872.0, 0.0, 0.0, 0.0, 116.45033264160156, 136.2347412109375, 0.2130783051252365, 0.01926681026816368, 1.1191160678863525, 104183, -1)], 
      dtype=[('x', '<f4'), ('y', '<f4'), ('z', '<f4'), ('vx', '<f4'), ('vy', '<f4'), ('vz', '<f4'), ('mvir', '<f4'), ('m200b', '<f4'), ('m200c', '<f4'), ('m500c', '<f4'), ('m2500c', '<f4'), ('vmax', '<f4'), ('rvmax', '<f4'), ('r200b', '<f4'), ('spin', '<f4'), ('kin_to_pot', '<f4'), ('id', '<i8'), ('pid', '<i8')])

don't mess with the offset, the offset searches inside the id list inside the whole "ds" full dataset and finds where the index for that particle is 

In [28]:
filtered_catalog.get_halo(136591)

HTTPSDFREAD
<type 'numpy.float64'>
1.0
<type 'numpy.ndarray'>
[0 0 0]


(2726.94287109375, 3072.8818359375, 641.2564697265625, -68.32164764404297, 105.40631103515625, 122.46353912353516, 927564558237696.0, 1000036024451072.0, 826901060911104.0, 647010919120896.0, 135844958568448.0, 1645.4683837890625, 971.8765869140625, 2.442671775817871, 0.045493233948946, 0.7754606604576111, 3573634164, -1)

In [29]:
def get_halo(self, n):
        ds = self.load()
        offset = ds['id'][n]
        catalog = self.parent[self.halo_catalog].load(midx = -1)
#         return catalog
        return  catalog.sdf_container.structs[-1][offset]
#         halo = catalog.sdf_container.structs[-1][offset][0]
#         return halo

In [31]:
get_halo(filtered_catalog,136591)[0]#[-1][136591]#[0]

HTTPSDFREAD
<type 'numpy.float64'>
1.0
<type 'numpy.ndarray'>
[0 0 0]


(2726.94287109375, 3072.8818359375, 641.2564697265625, -68.32164764404297, 105.40631103515625, 122.46353912353516, 927564558237696.0, 1000036024451072.0, 826901060911104.0, 647010919120896.0, 135844958568448.0, 1645.4683837890625, 971.8765869140625, 2.442671775817871, 0.045493233948946, 0.7754606604576111, 3573634164, -1)

is there a way to get the info about which particles are clustered together in which halo? 

In [32]:
filtered_catalog.parent

DarkSkyCatalog: ds14_a

In [33]:
filtered_catalog.halo_catalog

'halos_a_1.0000'

In [36]:
filtered_catalog.parent['halos_a_1.0000']

DarkSkySDFHaloCatalog: halos_a_1.0000

In [37]:
filtered_catalog.parent['halos_a_1.0000'].sdf_container.structs

AttributeError: 'DarkSkySDFHaloCatalog' object has no attribute 'sdf_container'

In [5]:
halo_info=np.array([1,2])
np.savetxt("halo_catalog.txt",halo_info)